name: CI on push

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-deps-

      - name: Get the version
        id: get_version
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/heads\/tags\//}

      - name: print version
        run: echo ${{ steps.get_version.outputs.TAG_NAME }}

      - run: npm set progress=false
      - run: npm ci
      - run: npm run lint
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test:single-run
      - run: npm run build:libs
